### ISSUE TITLE
error in configure

### ISSUE THREAD

**Issue by andyyuan78** [neubig/lader#4]
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for boostlib >= 1.38... yes
checking whether the Boost::System library is available... yes
configure: error: Could not find a version of the library!
ubgpu@ubgpu:~/github/lader$

**Comment by neubig** [comment]
Thanks for the report!
Unfortunately, I can't reproduce this in my environment, but if you debug this and find the reason why it broke, definitely send a pull request and I'll incorporate it.

**Comment by neubig** [comment]
Closed for lack of activity.

**Comment by andyyuan78** [comment]
fix by:

ubgpu@ubgpu:~/github/lader$ rm -rf autom4te.cache
ubgpu@ubgpu:~/github/lader$ ./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu

my system is ubuntu14.04
