### ISSUE TITLE
lader in server mode

### ISSUE THREAD

**Issue by vmando** [neubig/lader#7]
Is there an option to use lader in server mode? In fact, running a command like `bin/lader -model model.mod -out_format order,string -threads 32 -beam 1 -cube_growing true` once for each segment would take too much (3 minutes per segment).
Thanks

**Comment by neubig** [comment]
No, there is not a server mode, and there probably will not be a native server mode for lader in the near future. What I've done in the past is use this script, which converts an arbitrary command line argument into a server using XML-RPC:
https://github.com/neubig/util-scripts/blob/master/serverfy.pl

**Comment by vmando** [comment]
Do you have an example for the client script for calling serverfy.pl?

**Comment by vmando** [comment]
Thank you! That worked like a charm
